### ISSUE TITLE
1.5.0 no QR-code on x86&x64 Win compiled binaries

### ISSUE THREAD

**Issue by 2muaddlb** [Snawoot/nth-dump#9]
Example:

NTH-DUMP: 2022/11/02 17:34:41.586716 client.go:63: trying URL: "https://www.aba29108d294.info/getserver-190831.php?appVersion=5.1.0&id=68da20d4-5c08-4144-a582-09248ac3009a&key=Cxgh48fDSJhiWpk9&lang=en-US"

----------

Name:           nthLink Server
Host:           68.183.41.245
Port:           443
Method:         chacha20-ietf-poly1305
Password:       VRjVhWDlXZVG
URL:            ss://Y2hhY2hhMjAtaWV0Zi1wb2x5MTMwNTpWUmpWaFdEbFhaVkc=@68.183.41.245:443#nthLink%20Server

----------

Press ENTER to exit...

**Comment by Snawoot** [comment]
Hello!

On windows platform QR code generation is disabled by default because on Windows terminals it produces garbage instead of proper graphical output. You can try to force re-enable by adding command line option `-noqr=false` or convert URL into QR code yourself using any service producing QR codes like [this one](https://goqr.me/).

**Comment by 2muaddlb** [comment]
In Windows Terminal (in cmd/PS tab) it runs just fine! So I'd suggest implementing some line of code to detect environment the exe is being run in or just echo a message like "Run in Windows Terminal if you want to get a QR-code"
Thx a lot for this program! Much appreciated!
